# Generated by Django 5.2.5 on 2025-09-27 14:31
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroLivroModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("autor", models.CharField(max_length=50)),
                ("isbn", models.TextField(blank=True, null=True)),
                ("completo", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
