# Generated by Django 5.2.5 on 2025-09-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastrolivromodel",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cadastrolivromodel",
            name="emprestado",
            field=models.BooleanField(default=False),
        ),
    ]
