# Generated by Django 5.2.6 on 2025-09-30 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_cadastrolivromodel_data_devolucao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrolivromodel',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='cadastrolivromodel',
            name='emprestado',
        ),
        migrations.AddField(
            model_name='cadastrolivromodel',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=20),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='livros.cadastrolivromodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('data_devolucao__isnull', True)), fields=('livro',), name='unique_livro_emprestimo_ativo')],
            },
        ),
    ]
