# Generated by Django 5.2.6 on 2025-09-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_remove_cadastrolivromodel_data_devolucao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pronta', 'Disponível para retirada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('concluida', 'Concluída')], default='ativa', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pronta_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('expirada_em', models.DateTimeField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='livros.cadastrolivromodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ativa', 'pronta'])), fields=('livro', 'usuario'), name='unique_reserva_ativa_por_usuario')],
            },
        ),
    ]
