# Generated by Django 4.2.24 on 2025-10-22 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='dias_atraso',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='renovacao_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_saida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
