# Generated by Django 5.1.6 on 2025-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_remove_emprestimo_dias_atraso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='multa_paga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='multa_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
