# .github/workflows/fly-deploy.yml

name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  # -------------------- JOB 1: BUILD --------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Mantenha sua versão correta

      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app 
          path: . 
          
  # -------------------- JOB 2: DEPLOY --------------------
  deploy:
    name: Deploy app
    needs: build
    runs-on: ubuntu-latest
    concurrency: deploy-group
    
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # O passo de 'mv python-app/*' foi removido, corrigindo o erro anterior.
          
      # Setup do flyctl
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions@v1.4 # Caminho corrigido para o Action

      # **CORREÇÃO FINAL AQUI**: Remoção do argumento --remote-only
      - name: Deploy app
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
